version: '3.8'

services:
  db:
    image: postgres:14.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: rest_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: go_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: strongpassword
      DB_NAME: rest_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app # Bind the local directory to the container
    command: air # Use Air for hot reloading

volumes:
  postgres_data: